export const CONFIG_NAMES = {
  PEPPER_SECRET: 'PEPPER_SECRET',
  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRATION_TIME: 'JWT_EXPIRATION_TIME',
  JWT_REFRESH_EXPIRATION_TIME: 'JWT_REFRESH_EXPIRATION_TIME',
};
