export const CONFIG_NAMES = {
  // AUTH SECRET
  PEPPER_SECRET: 'PEPPER_SECRET',
  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRATION_TIME: 'JWT_EXPIRATION_TIME',
  JWT_REFRESH_EXPIRATION_TIME: 'JWT_REFRESH_EXPIRATION_TIME',

  // MAIL CONFIG
  MAIL_HOST: 'MAIL_HOST',
  MAIL_PORT: 'MAIL_PORT',
  MAIL_USER: 'MAIL_USER',
  MAIL_PASS: 'MAIL_PASS',
  MAIL_DEFAULT_FROM: 'MAIL_DEFAULT_FROM',
};
